Update thirdparty/cpanfile-5.34.snapshot: more modules in development/test builds
...and update the spell-checker for it:

* copy into a local file `x` the error text from e.g.
  https://github.com/jimklimov/znapzend/actions/runs/9337739109/job/25700004653
  section "spell check" with lines like

    Error: thirdparty/cpanfile-5.34.snapshot:17:20 ... 24, Error - `GARU` is not a recognized word. (unrecognized-spelling)

* mix with existing dictionary:

    ( cat x | sed -e 's,^[^`]*`,,' -e 's,`.*$,,' ; cat .github/workflows/spelling/expect.txt ) | sort -f | uniq | grep -vE '^$' > z
    cp z .github/workflows/spelling/expect.txt
    git add -p

Signed-off-by: Jim Klimov <jimklimov@gmail.com>